# Generated by Django 5.1.4 on 2025-01-11 15:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Topic',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='blog',
            new_name='topic',
        ),
    ]
