# Generated by Django 5.1.4 on 2025-01-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_topic_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='excerpt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
