# Generated by Django 5.1.4 on 2025-01-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_topic_excerpt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='is_draft',
        ),
        migrations.AddField(
            model_name='topic',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
