# Generated by Django 5.1.4 on 2025-01-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='category',
            field=models.CharField(choices=[('nuclear_facilities', 'Nuclear Facilities'), ('nuclear_defence', 'Nuclear Defence')], default='nuclear_facilities', max_length=200),
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
