# Generated by Django 5.1.4 on 2025-01-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_topic_category_delete_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.CharField(choices=[('nuclear_facilities', 'Nuclear Facilities'), ('nuclear_fuel_waste', 'Nuclear Fuel & Waste'), ('nuclear_defence', 'Nuclear Defence'), ('nuclear_power_space', 'Nuclear Power in Space'), ('fact_or_fiction', 'Fact or Fiction'), ('educational_resources', 'Educational Resources')], default='nuclear_facilities', max_length=200),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
    ]
