# Generated by Django 5.1.4 on 2025-01-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_topic_category_alter_topic_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
